### ISSUE TITLE
env variables to pass into the package

### ISSUE THREAD

**Issue by RanaivosonHerimanitra** [Alino/alino-mongo2es#1]
Newbie question here:
How to tell mongo2es my mongo url and replicat  set? Thanks

**Comment by Alino** [comment]
you need to set these two env variables for your whole meteor app:
MONGO_URL
MONGO_OPLOG_URL

**Comment by RanaivosonHerimanitra** [comment]
I've declared them in mup.json file. Is It right?

**Comment by Alino** [comment]
I never tried mup yet. To make sure they are really declared, on the server try to

``` javascript
console.log(process.env.MONGO_URL);
console.log(process.env.MONGO_OPLOG_URL);
```

I set my env variables locally for now, and I am doing it in a start shell script

```
export MONGO_URL=mongodb://$DOCKER_CONTAINERS_IP:27017/kuknito
export MONGO_OPLOG_URL=mongodb://$DOCKER_CONTAINERS_IP:27017/local
cd app
meteor run --settings settings.json --port 3000
```

this works for me

**Comment by RanaivosonHerimanitra** [comment]
ok, I'll try it and let you know

**Comment by RanaivosonHerimanitra** [comment]
I did the following steps:

```
$ export MONGO_URL="mongodb://xxxxx:xxx@candidate.45.mongolayer.com:xxx,candidate.50.mongolayer.com:zzzz/annuaire?replicaSet=set-fsjhfshjfhshf"
$ export MONGO_OPLOG_URL="mongodb://xxxxx:xxx@candidate.45.mongolayer.com:fsf,candidate.50.mongolayer.com:fdfdf/local?authSource=annuaire"
$  elasticsearchHost="https://fshfjhsfh.us-west-2.es.amazonaws.com" meteor run --settings settings.json --port 3000
```

That gives me this error:

```
W20160121-21:22:14.433(3)? (STDERR) logit host wasn't set. Logging into console only
W20160121-21:22:16.993(3)? (STDERR) 
W20160121-21:22:16.993(3)? (STDERR) /home/herimanitra/.meteor/packages/meteor-tool/.1.1.10.1205wux++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20160121-21:22:16.993(3)? (STDERR)                         throw(ex);

```

**Comment by Alino** [comment]
doesn't the error continue? This is hard for me to debug from this small message.

**Comment by RanaivosonHerimanitra** [comment]
Here is the full error message. I have both a collection called `corporation` stored in compose.io and in aws elasticsearch host.

```
W20160124-09:45:51.018(3)? (STDERR) logit host wasn't set. Logging into console only
W20160124-09:45:53.699(3)? (STDERR) 
W20160124-09:45:53.700(3)? (STDERR) /home/herimanitra/.meteor/packages/meteor-tool/.1.1.10.1205wux++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20160124-09:45:53.700(3)? (STDERR)                         throw(ex);
W20160124-09:45:53.701(3)? (STDERR)                               ^
W20160124-09:45:53.882(3)? (STDERR) Error: A method named '/corporation/insert' is already defined
W20160124-09:45:53.882(3)? (STDERR)     at livedata_server.js:1542:15
W20160124-09:45:53.882(3)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
W20160124-09:45:53.882(3)? (STDERR)     at [object Object]._.extend.methods (livedata_server.js:1538:7)
W20160124-09:45:53.882(3)? (STDERR)     at [object Object].Mongo.Collection._defineMutationMethods (packages/mongo/collection.js:927:1)
W20160124-09:45:53.883(3)? (STDERR)     at new Mongo.Collection (packages/mongo/collection.js:218:1)
W20160124-09:45:53.883(3)? (STDERR)     at Mongo2ES.Mongo2ES.getCollection (packages/alino_mongo2es/lib/mongo2es.coffee:24:51)
W20160124-09:45:53.883(3)? (STDERR)     at new Mongo2ES (packages/alino_mongo2es/lib/mongo2es.coffee:7:40)
W20160124-09:45:53.883(3)? (STDERR)     at server/paypal_config.js:21:1
=> Exited with code: 8
W20160124-09:45:53.883(3)? (STDERR)     at /home/herimanitra/Documents/annuaire_v2/.meteor/local/build/programs/server/boot.js:249:5
W20160124-09:46:00.604(3)? (STDERR) logit host wasn't set. Logging into console only
W20160124-09:46:03.290(3)? (STDERR) 
W20160124-09:46:03.291(3)? (STDERR) /home/herimanitra/.meteor/packages/meteor-tool/.1.1.10.1205wux++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20160124-09:46:03.291(3)? (STDERR)                         throw(ex);
W20160124-09:46:03.291(3)? (STDERR)                               ^
W20160124-09:46:03.429(3)? (STDERR) Error: A method named '/corporation/insert' is already defined
W20160124-09:46:03.429(3)? (STDERR)     at livedata_server.js:1542:15
W20160124-09:46:03.429(3)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
W20160124-09:46:03.429(3)? (STDERR)     at [object Object]._.extend.methods (livedata_server.js:1538:7)
W20160124-09:46:03.429(3)? (STDERR)     at [object Object].Mongo.Collection._defineMutationMethods (packages/mongo/collection.js:927:1)
W20160124-09:46:03.429(3)? (STDERR)     at new Mongo.Collection (packages/mongo/collection.js:218:1)
W20160124-09:46:03.429(3)? (STDERR)     at Mongo2ES.Mongo2ES.getCollection (packages/alino_mongo2es/lib/mongo2es.coffee:24:51)
W20160124-09:46:03.429(3)? (STDERR)     at new Mongo2ES (packages/alino_mongo2es/lib/mongo2es.coffee:7:40)
W20160124-09:46:03.430(3)? (STDERR)     at server/paypal_config.js:21:1

```

**Comment by Alino** [comment]
please paste here how you set up your watchers.

I think the problem is that you have already defined your Mongo collection somewhere in your project
something like

``` javascript
corporation = new Mongo.Collection('corporation')
```

and now if you want to use that collection in your Mongo2ES watcher, you should **pass the collectionName not as a string but as variable** `corporation` which is Mongo.Collection object you created earlier in your project.

**Comment by RanaivosonHerimanitra** [comment]
Yes, corporation had been already defined. The following code is inside a `server` folder. 

```
if(Meteor.isServer) {
  Meteor.startup(function() {

options = {
  collectionName: corporation,
  ES: {
    host: Meteor.settings.elasticsearchHost,
    index: "corporation",
    type: "enterprise"
  },
  transform: undefined,
  copyAlreadyExistingData: false 
// Boolean - true if  it should copy all existing data in this collection ( default: false )
}
    new Mongo2ES(options);
  });
}
```

and now, `logit host wasn't set. Logging into console only`

```
=> Started proxy.                             
W20160124-16:57:31.327(3)? (STDERR) logit host wasn't set. Logging into console only
W20160124-16:57:34.333(3)? (STDERR) 
W20160124-16:57:34.334(3)? (STDERR) /home/herimanitra/.meteor/packages/meteor-tool/.1.1.10.1205wux++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20160124-16:57:34.335(3)? (STDERR)                         throw(ex);
W20160124-16:57:34.335(3)? (STDERR)                               ^
W20160124-16:57:34.341(3)? (STDERR) ReferenceError: corporation is not defined
W20160124-16:57:34.341(3)? (STDERR)     at server/paypal_config.js:11:1
W20160124-16:57:34.341(3)? (STDERR)     at /home/herimanitra/Documents/annuaire_v2/.meteor/local/build/programs/server/boot.js:249:5

```

**Comment by Alino** [comment]
`logit host wasn't set. Logging into console only` is just a warning which you can ignore. Unless you want to log into Logstash.

But regarding the other error `ReferenceError: corporation is not defined` check out how you defined your 'corporation' collection in Meteor. Figure out why it is not defined, maybe the first letter is uppercase `Corporation`

**Comment by RanaivosonHerimanitra** [comment]
Stupid error, It was `Corporation` , thank you so much
